import java.io.PrintWriter;

public class DXFWriter {
    public static void writeHeader(PrintWriter writer) {
        writer.printf("0\nSECTION\n");
        writer.printf("2\nHeader\n");
        writer.printf("0\nENDSEC\n");
        writer.printf("999\nGenerated by DXF class of CycloidApplet\n");
        writer.printf("0\nSECTION\n");
        writer.printf("2\nENTITIES\n");
        writer.flush();
    }
    public static void writeTrailer(PrintWriter writer) {
        writer.printf("0\nENDSEC\n");
        writer.printf("0\nEOF\n");
        writer.flush();
    }
    public static void write2DLine(PrintWriter writer, double x1, double y1, double x2, double y2) {
        writer.printf("0\nLINE\n");
        writer.printf("8\n0\n");
        writer.printf("10\n%9.7f\n",x1);
        writer.printf("20\n%9.7f\n",y1);
        writer.printf("11\n%9.7f\n",x2);
        writer.printf("21\n%9.7f\n",y2);
        writer.flush();
    }
    public static void write2DPolyLine(PrintWriter writer, int n, Points points) {
        writer.printf("0\nPOLYLINE\n");
        writer.printf("8\n0\n");
        writer.printf("66\n1\n");
        writer.printf("10\n0.000000\n");
        writer.printf("20\n0.000000\n");
        for (int i=0; i<n; i++) {
            writer.printf("0\nVERTEX\n");
            writer.printf("8\n0\n");
            writer.printf("10\n%9.7f\n", points.getPoints().get(i).X);
            writer.printf("20\n%9.7f\n", points.getPoints().get(i).Y);
        }
        writer.printf("0\nSEQEND\n");
        writer.printf("8\n0\n");
        writer.flush();
    }
}
